version: "3"

services: 
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
     - 9092:9090
    volumes: 
     - ./prometheus:/etc/prometheus
    networks:
      - prometheus
networks:
  prometheus:
   name: prometheus