version: "3"
volumes:
  prometheus-data: {}
services: 
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
     - 9092:9090
    volumes: 
     - ./prometheu:/etc/prometheus
     - prometheus-data:/prometheus
    networks:
      - prometheus
networks:
  prometheus:
   name: prometheus
