services:
    web:
        image: kubedevio/rotten-potatoes:v1
        ports:
                - 4000:5000
        networks:
            - prometheus
        depends_on:
            - mongodb
        environment:
            MONGODB_DB: "admin"
            MONGODB_HOST: "mongodb"
            MONGODB_PORT: 27017
            MONGODB_USERNAME: "admin"
            MONGODB_PASSWORD: "adminpwd"
    mongodb:
        image: mongo:7.0
        volumes:
            - db_mongo:/data/db
        networks:
            - prometheus
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "adminpwd"
    prometheus:
        image: prom/prometheus:latest
        ports:
            - 9092:9090
        networks:
            - prometheus
        volumes:
            - ./prometheus.yaml:/etc/prometheus/prometheus.yml
networks:
    prometheus:
        driver: bridge
volumes:
    db_mongo:
